  name: Build & Deploy backend

  on:
    push:
      branches:
        - master

  jobs:
    build-deploy:

      name: Build and Deploy Backend for portfolio
      runs-on: ubuntu-24.04
      services:
        mysql:
          image: mysql:8.0
          env:
            MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
            MYSQL_DATABASE: portfolio
            ports:
              -3306:3306
            options: >-
              --health-cmd "mysqladmin ping -h 127.0.0.1 -u root -p${{secrets.MYSQL_ROOT_PASSWORD}}"
              --health-interval 10s
              --health-timeout 5s
              --health-retries 10
      steps:
        - name: checkout code
          uses: actions/checkout@v5

        - name: wait for mysql db to be ready
          run:  sleep 10


        - name: Setup Nodejs
          uses: actions/setup-node@v5
          with: 
            node-version: 24.5.0

        - name: Unit Tests
          run: npm install && npm test -- --runInBand
          env:
            DB_HOST: 127.0.0.1
            DB_USER: root
            DB_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
            DB_NAME: portfolio
            DB_PORT: 3306
            APP_SECRET: helloworld123
            USER_EMAIL: crazyUser123@gmail.com
            USER_PASSWORD: Crazypassword123!

        - name: Build the application
          run: |
            curl https://cli-assets.heroku.com/install.sh | sh
        - uses: akhileshns/heroku-deploy@v3.14.15
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            
